### ISSUE TITLE
cluster_stat quebrado no Ubuntu 16

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/abacus#1]
O script cluster_stat não está funcionando na versão mais nova. No Ubuntu 12:

```
abacus0000:     CPU use: 1.2%       Mem use: 1.55%      Jobs from: 
abacus0001:     CPU use: 0%     Mem use: 1.54%      Jobs from: 
abacus0002:     CPU use: 0%     Mem use: 1.53%      Jobs from: 
abacus0003:     CPU use: 1.2%       Mem use: 1.52%      Jobs from: 
(...)
```

No Ubuntu 16:

```
 abacus0016:        top: bad delay interval '0.1'
 CPU use: %     Mem use: 1.48%      Jobs from: chalom
 abacus0018:        top: bad delay interval '0.1'
 CPU use: %     Mem use: 1.47%      Jobs from: chalom
 abacus0021:        top: bad delay interval '0.1'
 CPU use: %     Mem use: 1.55%      Jobs from: chalom
```

Note que eu não tenho jobs ativos nesses nós!

Assim, os erros são: não está reportando corretamente o CPU use (pq a interface com o top está com erro) e está reportando incorretamente o usuário que executa o comando como se ele estivesse executando jobs em todos os nós.

**Comment by renatocoutinho** [comment]
Sobre o bug com usuário, pelo que vi, a culpa é desses processos do systemd:

`/lib/systemd/systemd --user`
`(sd-pam)`

que rodam sem indicar o tty. Mais um grep no local_stat pra excluir esses processos da detecção deve resolver, espero.

Já a interface com o top, a coisa é simples também: a linha relevante do top agora começa com "%Cpu", não apenas "Cpu", então o grep no local_stat teria que usar o primeiro. Pra não dar erro nos nós antigos, precisa usar 2 patterns no grep:

`grep -e "^%Cpu" -e "^Cpu"`

**Comment by Lobz** [comment]
Sobre o bug da %Cpu, a sintaxe do top muda um pouco nos nós com pxe.
Top do nó 18:```
top - 16:15:48 up 13 days, 21:58,  1 user,  load average: 0.00, 0.00, 0.00
Tasks: 144 total,   1 running, 143 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8164844 total,  7758528 free,    60376 used,   345940 buff/cache
KiB Swap:  2440188 total,  2440188 free,        0 used.  7829848 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0   37824   6024   4144 S   0.0  0.1   0:05.22 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd

```
top do nó 00:
```

top - 16:16:51 up 13 days, 22:07,  1 user,  load average: 0.02, 0.04, 0.05
Tasks: 123 total,   1 running, 122 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.1%us,  0.1%sy,  0.0%ni, 99.8%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  16340472k total,   486024k used, 15854448k free,   123836k buffers
Swap:  2440188k total,        0k used,  2440188k free,    96976k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  973 root      20   0  973m 2484 1340 S    2  0.0 485:02.43 aprsd
    1 root      20   0 24420 2412 1344 S    0  0.0   0:01.13 init
    2 root      20   0     0    0    0 S    0  0.0   0:00.03 kthreadd

```
A regex que está lendo a linha do Cpu está esperando que cada valor seja seguido de %, o que não acontece no PXE.

Obs.: não encontrei essa mensagem de "bad delay interval" 


```

**Comment by Lobz** [comment]
Adicionei os scripts no repositório, já corrigidos.

Estamos ignorando os processos "systemd --user" e "(sd-pam)".

**Comment by Lobz** [comment]
Ok já subi o script modificado
