### ISSUE TITLE
Configurações para novos usuários

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/abacus#11]
[EDIT: atualizando com lista de arquivos de configuração sugeridos pelo @renatocoutinho]

- [X] .bashrc (aumentei o HISTORY, forcei color prompt, completion já está ativado)
- [X] .nanorc / R.nanorc (incluído em /usr/local/share)
- [X] .screenrc
- [ ] .tmux.conf (não inclui as do /home/renato pois há uma longa série de key rebindings, acho que vai atrapalhar mais do que ajudar novos usuários)
- [ ] incluir um known_hosts padrão incluindo todos os nós [aguardando os nós estarem ativos]
- [ ] Testar essas configurações com um usuário novo

**Comment by renatocoutinho** [comment]
Não vejo por que não, evita uma confusão inicial pra usar paralelização e cluster_stat.

**Comment by andrechalom** [comment]
Vou esperar os nós 18 e 22 estarem no ar de novo para gerar um known_hosts então.

E o que vc recomenda em termos de bashrc, nanorc, screenrc?

**Comment by renatocoutinho** [comment]
- bashrc precisa de um prompt mais bonitinho que realce o hostname, sem contar coisas simples como completion e histórico maior
- nanorc precisa de syntax highlight (bizarramente isso não é default)
- screenrc precisa de uma linha de status, pra ver quantos shells tem na screen e em qual você está (mais uma vez, bizarramente isso não é o padrão)
- recentemente comecei a usar tmux (análogo do screen), basicamente porque o vim-R depende dele, e parece muito bom também. Precisa instalar nos nós (tem só no master)

**Comment by renatocoutinho** [comment]
Se quiser, pode usar minhas configurações (.screenrc, .tmux.conf, .nanorc), acho que não fiz nada muito absurdo com elas, com exceção do .bashrc, que tem muita frescura ("idiossincrasias" hahaha) herdada de anos e anos...

No meu home tem um .nano/R.nanorc (que não vem no pacote do Ubuntu) que acho que vale a pena colocar numa pasta do sistema também (ou no home de cada user?). Recomendo tranquilamente nano ao invés de vim/emacs pra iniciantes, mas essa falta de cores me incomoda muito.
