### ISSUE TITLE
Software

### ISSUE THREAD

**Issue by renatocoutinho** [lageIBUSP/abacus#13]
Issue para pedir a instalação de pacotes.

No momento não tem nenhuma das ferramentas pra rodar cálculos em python:
* ipython3
* python{,3}-numpy
* python{,3}-scipy
* python{,3}-matplotlib
* python{,3}-pandas

Além disso, gostaria de ter `tmux` nos nós (na verdade, só vai ser realmente útil pra mim quando tiver vim>=8.0, versão mínima pra usar Nvim-R).

**Comment by andrechalom** [comment]
Tudo instalado, por favor verifique :)

**Comment by renatocoutinho** [comment]
Beleza, valeu!
