### ISSUE TITLE
cluster_stat não reporta jobs com usernames longos

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/abacus#17]
Quando o nome do usuário é muito longo, o `ps` indica apenas os primeiros caracteres, o que faz o cluster_stat não reconhecer como nome de usuário válido.

**Comment by renatocoutinho** [comment]
Dá pra passar o formato de output pro ps. Infelizmente isso te força a especificar todas as colunas, mas enfim:

    ps axo user:20,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,comm

**Comment by andrechalom** [comment]
Maravilha :)

Valeuzão!
