### ISSUE TITLE
Migrar scripts para esse repositório

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/abacus#2]
Scripts de administração, arquivos padronizados e documentação devem ser migrados para este repositório.

Talvez a documentação deva ser servida como gh-pages?

**Comment by andrechalom** [comment]
- [x] DOCUMENTAÇÃO: precisa ficar claro que os nós 0-15 estão em 220V e os nós 16-23 estão em 110V. Isso precisa estar na documentação online E em placas no local!

**Comment by Lobz** [comment]
scripts e configuração migrados

**Comment by andrechalom** [comment]
Migração da documentação em progresso! Terminando, precisamos remover as externas para evitar duplicação

**Comment by andrechalom** [comment]
- [x] Documentar aqui os scripts "caseiros" (all pall cluster_stat e wake)
