### ISSUE TITLE
Instalar PXE

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/abacus#3]
Configurar o PXE no cluster.

**STATUS**: funcional em todos os nós! [Edit: 10/11]

Tarefas:
- [x] Documentar corretamente o processo de instalação do PXE+NFS.
- [x] Fazer com que os nós peguem o hostname a partir do DHCP _OU_ do IP designado.
- [x] Decidir como gerenciar diretorios que podem sofrer escrita concorrente de vários nós, como /var/log
- [x] Decidir como gerenciar upgrades de sistema operacional
- [x] Verificar se o gerenciamento de usuários por NIS está funcionando bem.
- [x] Verificar se o gerenciamento de data/hora por ntpdate está funcionando bem.
- [x] Garantir que passwordless ssh funciona bem.
- Verificar se as seguintes coisas funcionam bem: 
- [x] Scripts de R usando library(parallel)
- [ ] Programas em C usando Open MPI
- [x] RAxML??

**Comment by andrechalom** [comment]
Questões:

- Como gerenciar diretorios que tem escrita? (/var/log)
- Como gerenciar upgrades de sistema operacional?
- Como gerenciar usuários? NIS?
- Como gerenciar data/hora - ntpdate?
- Garantir que passwordless ssh funciona
- Open MPI

**Comment by andrechalom** [comment]
- [ ] NIS não está funcionando
- [ ] Rebootar nós com IP errado
- [ ] Fazer os nós pegarem o hostname do DHCP
- [ ] Login está extreeeeemamente lento

**Comment by andrechalom** [comment]
[ Essa documentação foi migrada para wiki ]

**Comment by Lobz** [comment]
Estou configurando o log do PXE pra se distribuir em diretórios /var/log/abacus00XX.

Documentando:
Criei os diretórios /var/log/abacus0000-...23 e mudei o grupo deles para `adm` e o owner pra `syslog` para evitar problemas de permissão.
Criei um arquivo /etc/rsyslog.d/10-perhostname.conf, a ser subido aqui no repositório, reproduzindo as configurações de log padrão, só que usando templates para usar hostname no path dos arquivos.
Estou pensando em remover as regras de log default, já que eles não estão funcionando (só o 0006 está logando)

Falta: configurar o rotate

Referências:
[How to separate log files by host name of sending device?](http://www.rsyslog.com/article60/)
[How To View and Configure Linux Logs on Ubuntu and Centos](https://www.digitalocean.com/community/tutorials/how-to-view-and-configure-linux-logs-on-ubuntu-and-centos)
[Setup for rsyslog to log from two network devices](http://superuser.com/questions/997575/setup-for-rsyslog-to-log-from-two-network-devices?rq=1)
[rsyslog Properties](http://www.rsyslog.com/doc/master/configuration/properties.html)

**Comment by Lobz** [comment]
Configurei o logrotate do master para rotacionar os logs dos nós para evitar o problema de gerenciar quem vai rotacionar o quê

**Comment by andrechalom** [comment]
Migrar nós da segunda coluna (08-15) está gerando dificuldades, talvez info aqui:

https://github.com/openSUSE/kiwi/wiki/Setup-PXE-boot-with-EFI-Using-GRUB2
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/s1-netboot-pxe-config-efi.html
https://wiki.ubuntu.com/UEFI/PXE-netboot-install
https://en.wikipedia.org/wiki/Preboot_Execution_Environment

Ligar debug logs no dnsmasq:
http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2005q2/000288.html

**Comment by andrechalom** [comment]
- [x] Falta documentar a questão dos logs na wiki.
